### ISSUE TITLE
reliability: asyncio.exceptions.TimeoutError makes the test exist

### ISSUE THREAD

**Issue by qiliRedHat** [openshift/svt#687]
I met this exception when app can not be reached (cluster can not be reached at that time),  socket.gaierror: [Errno 8] nodename nor servname provided, or not known. Should catch this exception to avoid test exists.

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1245, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1291, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 948, in send
    self.connect()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1407, in connect
    super().connect()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 919, in connect
    self.sock = self._create_connection(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reliability.py", line 40, in <module>
    task_manager.start()
  File "/Users/qili/git/svt/reliability/tasks/TaskManager.py", line 190, in start
    task.execute()
  File "/Users/qili/git/svt/reliability/tasks/Task.py", line 189, in execute
    for result in results:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/qili/git/svt/reliability/tasks/Task.py", line 188, in <lambda>
    results = executor.map(lambda t: all_apps.apps[t[0]].scale_up(t[1]), app_scale_args)
  File "/Users/qili/git/svt/reliability/tasks/Apps.py", line 39, in scale_up
    (result, rc) = oc("scale --replicas=2 -n " + self.project + " dc/" + self.deployment, kubeconfig)
  File "/Users/qili/git/svt/reliability/tasks/utils/oc.py", line 30, in oc
    result,rc = shell(cmd)
  File "/Users/qili/git/svt/reliability/tasks/utils/oc.py", line 17, in shell
    slackIntegration.post_message_in_slack(f"cmd: {cmd}  failed. Result: {result_decode}")
  File "/Users/qili/git/svt/reliability/tasks/utils/SlackIntegration.py", line 56, in post_message_in_slack
    self.slack_client.chat_postMessage(
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/slack/web/client.py", line 1077, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/slack/web/base_client.py", line 150, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/slack/web/base_client.py", line 241, in _sync_send
    return self._urllib_api_call(
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/slack/web/base_client.py", line 352, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/slack/web/base_client.py", line 495, in _perform_urllib_http_request
    raise err
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/slack/web/base_client.py", line 475, in _perform_urllib_http_request
    resp = urlopen(  # skipcq: BAN-B310
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
Task exception was never retrieved
future: <Task finished name='Task-61339' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 20, in get
    result = await response.text()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61342' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61345' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61418' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61421' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61423' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61427' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61428' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61429' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61430' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61431' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61432' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61434' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61435' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61446' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 20, in get
    result = await response.text()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61451' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 20, in get
    result = await response.text()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61453' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 18, in get
    async with session.get(url) as response:
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Task exception was never retrieved
future: <Task finished name='Task-61455' coro=<LoadApp.get() done, defined at /Users/qili/git/svt/reliability/tasks/utils/LoadApp.py:15> exception=TimeoutError()>
Traceback (most recent call last):
  File "/Users/qili/git/svt/reliability/tasks/utils/LoadApp.py", line 20, in get
    result = await response.text()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
  File "/Users/qili/virtualenv/reliability/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by qiliRedHat** [comment]
https://github.com/openshift/svt/pull/688
